
# See https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "waku-1245-cloudflare-wasm"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_als" ]
main = "./dist/worker/serve-cloudflare.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"
html_handling = "drop-trailing-slash"
# "single-page-application" | "404-page" | "none"
not_found_handling = "404-page"
